server {
    listen 80;
    listen [::]:80;
    server_name noura-store.com www.noura-store.com;

    root /var/www/noura-store;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
